dataset_path: D:\SEGMENTACJA IBM\plemniki\SegSperm_part\SegSperm_part
save_model_path: D:\SEGMENTACJA IBM\plemniki\save_model
save_fig_path: D:\SEGMENTACJA IBM\plemniki\save_fig
save_mask_path: D:\SEGMENTACJA IBM\plemniki\soft_masks

image_width: 512
image_height: 512